Optimizations
hms-dbmi/Access-to-Data-using-PIC-SURE-API pull request #76
Opened 2023-01-25 22:02 UTC by simranmakwana

2023-02-02 16:14 UTC, emhug reviewed
Tested all RStudio files on AIM-AHEAD SWB Prod. All were able to be run with some slight install code changes. ORCHID did not work due to issues of installing CMAKE, but that is a change that will be deployed to prod in the near future.

2023-02-02 19:41 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +Now, let's find all of the variables associated with that study. We can search for these using the `searchPicsure` function and searching the phs accession number. We are interested in the values ass
Resolved [0c5caed](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/0c5caed7d4ab85bb0a8ca44d7827a0457b9f99fb)

2023-02-02 19:42 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                     type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved: [72985f3](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/72985f3cb1e14c0aaeeec2da786ef3f97e687b6e)

2023-02-02 19:44 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +colnames(my_variables_df)
Resolved: [6460938](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/646093887170505b1f32d7943f615e23b369b75b)

2023-02-02 19:45 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                   type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved: [04856e8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/04856e8a0ad48d7ed10ae3a76586b4819adedaad)

2023-02-02 19:48 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +head(my_variables_df)
Resolved: [b033943](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/b03394315724ca2fada7ad7014c76fe712ec6b7f)

2023-02-02 19:49 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +Tthe output shown above lists all of the phs accession numbers and consent codes that you are authorized to access.
Resolved: [15e0cf6](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/15e0cf6fa0934a15f02fcd5d5d5c815fc62f0055)

2023-02-02 19:53 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
> +    mutate(varname_noexam = str_trim(str_replace(var_description, regex('exam \\d+|visit \\d+', ignore_case = 'T'), '')))
Resolved: [5851e64](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/5851e645c5e4424035d76ae015eace225839ca9a)

2023-02-02 19:53 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
> +    mutate(exam_number = toupper(str_trim(str_extract(var_description, regex('exam \\d+|visit \\d+', ignore_case = 'T')))))
Resolved: [5851e64](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/5851e645c5e4424035d76ae015eace225839ca9a)

2023-02-02 19:54 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/6_Sickle_Cell.Rmd
>  Sys.setenv(TAR = "/bin/tar")
Rejected: This is necessary info for the SB user

2023-02-02 19:57 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
> +eclipse_sex_df$name
Resolved: [42c938d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/42c938d343976a4b5335efdf1703162964601fc1)

2023-02-02 19:58 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
Resolved: [42c938d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/42c938d343976a4b5335efdf1703162964601fc1)

2023-02-02 19:58 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
> +Next, we add the paths (names) for our selected variabels of interest to the query.
Resolved: [42c938d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/42c938d343976a4b5335efdf1703162964601fc1)

2023-02-02 19:58 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
> +c(unique(orthopnea_results$orthopnea),
Resolved: [42c938d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/42c938d343976a4b5335efdf1703162964601fc1)

2023-02-03 15:14 UTC, RaePayne03 reviewed
Simran, I made some comments in the notebooks - mostly spelling/grammar changes. Looks great! Well done!

2023-02-08 16:52 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/R/1_PICSURE_API_101.ipynb
>     ]
This will depend on user data access

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +The first step to this is setting up the query object.
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                     type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                   type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
>  hist(full_results_continuous[,eval(continuous_var)],
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +Tthe output shown above lists all of the phs accession numbers and consent codes that you are authorized to access.
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
>  consent_group_filter <- "phs000964.c1"#"<<<Paste consent group here you are authorized to access here>>>"
Resolved in rstudio: [32bfcaf](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/32bfcaf05de59ed8fe9c9bfa8d0bb3500c78cef1)

2023-02-08 17:06 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
Resolved in rstudio: [7f36274](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/7f36274d8fef1265e7e1af012671058adb636aab)

2023-02-08 17:06 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
Resolved in rstudio: [7f36274](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/7f36274d8fef1265e7e1af012671058adb636aab)

2023-02-08 17:06 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
>  We can now see our 44 harmonized variables. This is in line with the [DCC Harmonized Variables documentation](https://github.com/UW-GAC/topmed-dcc-harmonized-phenotypes).
Resolved in rstudio: [7f36274](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/7f36274d8fef1265e7e1af012671058adb636aab)

2023-02-08 17:06 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
> +## 3. Visualizing our sex and race harmonized variables across study cohorts
Resolved in rstudio: [7f36274](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/7f36274d8fef1265e7e1af012671058adb636aab)

2023-02-08 17:06 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
>  Below, we wrangle the data to calculate the male/female sex ratio per study cohort and prepare our data for plotting.
Resolved in rstudio: [7f36274](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/7f36274d8fef1265e7e1af012671058adb636aab)

2023-02-08 17:11 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
>  # PheWAS analysis
Resolved in rstudio: [9c99755](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9c99755290c94eec26b341b2fe330126ce571455)

2023-02-08 17:11 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
Resolved in rstudio: [9c99755](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9c99755290c94eec26b341b2fe330126ce571455)

2023-02-08 17:11 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
>  ```{r}
Resolved in rstudio: [9c99755](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9c99755290c94eec26b341b2fe330126ce571455)

2023-02-08 17:19 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  We can further narrow our query by filtering on variant consequence. Let's look at missense variants in this example.
Resolved for rstudio: [c6d354d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/c6d354db106e6421bf447ac86057fecdd214618f)

2023-02-08 17:19 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  Let's explore what genes we can filter our variants by by looking at the values associated with the `Gene_with_variant` annotation.
Resolved for rstudio: [c6d354d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/c6d354db106e6421bf447ac86057fecdd214618f)

2023-02-08 17:19 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  ## 1.2 Add categorical phenotypic variable (sex) to the query
Resolved for rstudio: [c6d354d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/c6d354db106e6421bf447ac86057fecdd214618f)

2023-02-08 17:19 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  # Example 1: Walkthrough on building a query with genomic and phenotypic varibles
Resolved for rstudio: [c6d354d](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/c6d354db106e6421bf447ac86057fecdd214618f)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  Now that we know which longitudinal variables are available to us, we can choose a variable of interest and extract the patient and visit level data associated with it.
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  Now we save the variable name without the exam number as `varname_noexam`. This prepares us for the next step, where we will group the data by the variable name root.
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  We are interested in variables from the Framingham Heart Study. The PHS number associated with this study is `phs000007`. If you don't know the PHS number for a study of interest, you can check the D
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  First, let's search the data dictionary in PIC-SURE. We will use a regular expression for the search term: `lipid|trigliceride`. This allows us to find all variables related to `lipid` *or* `triglice
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  ## Longitudinal Lipid Variable Example
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:23 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
Resolved in rstudio: [9e2cc76](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/9e2cc76a1d05161894e9a6c8bd2209f3dbe0cc25)

2023-02-08 17:25 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/6_Sickle_Cell.Rmd
>  Once our query object is finally built, we use the `query.run` function to retrieve the data corresponding to our query
Resolved in rstudio: [97bf134](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/97bf134fa8d670607eae1e7fc4eec24dfe79b51e)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  We create a consistent mapping:
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  You can get the phs number associated with each study from the Data Access Dashboard.
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  As a reminder, these are the paths associated to the sex/gender and BMI variables from ECLIPSE and EOCOPD.
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  First, we create a new query:
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  We then filter to only those BMI variables which are part of ECLIPSE or EOCOPD and view the variables with their associated metadata.
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:29 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
> +Next, we add the paths (names) for our selected variabels of interest to the query.
Resolved in rstudio: [65c5f2f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/65c5f2fc8243d41f48b9ba91276b32b7bc06598f)

2023-02-08 17:35 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  ---
This notebook is the most advanced example notebook we have, that replicates a published study - I think it is okay for it to have less explanation.

2023-02-08 17:36 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  # Packages Installation
library(forcats) already is in the code

2023-02-08 17:36 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  # Outcome Analysis
Resolved for rstudio: [19abcbc](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/19abcbc8b6ee99af7abf469786918e3e00996fd0)

2023-02-08 17:36 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  This cell rename signification of the variables that are being used throughout the notebook.
Resolved for rstudio: [19abcbc](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/19abcbc8b6ee99af7abf469786918e3e00996fd0)

2023-02-08 18:20 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/R/7_Harmonization_with_PICSURE.ipynb
>    {
If this is a warning and not an error it should be fine

2023-02-08 20:05 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/R/1_PICSURE_API_101.ipynb
>     ]
Depends on user's access

2023-02-09 21:38 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
>  consent_group_filter <- "phs000964.c1"#"<<<Paste consent group here you are authorized to access here>>>"
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:39 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +Tthe output shown above lists all of the phs accession numbers and consent codes that you are authorized to access.
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:39 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
>  hist(full_results_continuous[,eval(continuous_var)],
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:39 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:39 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
>  ## About Harmonized Variables
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:40 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:40 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                   type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:40 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +                                                     type = 'REQUIRE') # use type = REQUIRE to retreive all data from pariticipants with a value for this variable
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:40 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
> +The first step to this is setting up the query object.
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:44 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:44 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
>  ## About Harmonized Variables
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:45 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:45 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
>  We can now see our 44 harmonized variables. This is in line with the [DCC Harmonized Variables documentation](https://github.com/UW-GAC/topmed-dcc-harmonized-phenotypes).
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:50 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/2_TOPMed_DCC_Harmonized_Variables_analysis.Rmd
> +## 3. Visualizing our sex and race harmonized variables across study cohorts
Resolved in R: [35eb60b](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/35eb60be8f0009721f8c02640d6b970eb9caa5ff)

2023-02-09 21:51 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
>  # PheWAS analysis
Resolved in R: [6f9e5d9](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/6f9e5d925847c30a25adadbf00acd4802a2a7d4d)

2023-02-09 21:52 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
Resolved in R: [6f9e5d9](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/6f9e5d925847c30a25adadbf00acd4802a2a7d4d)

2023-02-09 21:52 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/3_PheWAS.Rmd
>  ```{r}
Resolved in R: [6f9e5d9](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/6f9e5d925847c30a25adadbf00acd4802a2a7d4d)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  # Example 1: Walkthrough on building a query with genomic and phenotypic varibles
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  ## 1.2 Add categorical phenotypic variable (sex) to the query
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  Let's explore what genes we can filter our variants by by looking at the values associated with the `Gene_with_variant` annotation.
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  We can further narrow our query by filtering on variant consequence. Let's look at missense variants in this example.
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/4_Genomic_Queries.Rmd
>  This is a great way to preview how many participants match your query criteria without extracting all of the data yet.
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 21:56 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
Resolved for R: [cbc55af](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/cbc55af085a5a2e629558eafa5e1fdcad92071e7)

2023-02-09 22:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:00 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  ## Longitudinal Lipid Variable Example
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:01 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  First, let's search the data dictionary in PIC-SURE. We will use a regular expression for the search term: `lipid|trigliceride`. This allows us to find all variables related to `lipid` *or* `triglice
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:01 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  We are interested in variables from the Framingham Heart Study. The PHS number associated with this study is `phs000007`. If you don't know the PHS number for a study of interest, you can check the D
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:01 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  Now we save the variable name without the exam number as `varname_noexam`. This prepares us for the next step, where we will group the data by the variable name root.
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:01 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/5_LongitudinalData.Rmd
>  Now that we know which longitudinal variables are available to us, we can choose a variable of interest and extract the patient and visit level data associated with it.
Resolved in R: [dd0c9d0](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/dd0c9d061fabbb6d1edcd2662cfa833ffc57f948)

2023-02-09 22:05 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/6_Sickle_Cell.Rmd
>  We are also interested in the patients' age at which they received their transplant. However, we do not want to filter our cohort based on these values. We can use the query.select method to add this
Resolved in R: [4d0a7ef](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/4d0a7ef2ed6e87192abeab04a4f811641379e1b5)

2023-02-09 22:05 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/6_Sickle_Cell.Rmd
>  Once our query object is finally built, we use the `query.run` function to retrieve the data corresponding to our query
Resolved in R: [4d0a7ef](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/4d0a7ef2ed6e87192abeab04a4f811641379e1b5)

2023-02-09 22:12 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  Let's start by searching for `sex` and `gender` to gain a better understanding of the variables that exist in PIC-SURE with these terms. The `bdc::find.in.dictionary()` function can take in regular e
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:12 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:12 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  We then filter to only those BMI variables which are part of ECLIPSE or EOCOPD and view the variables with their associated metadata.
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:12 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  First, we create a new query:
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:13 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
> +Next, we add the paths (names) for our selected variabels of interest to the query.
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:13 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  As a reminder, these are the paths associated to the sex/gender and BMI variables from ECLIPSE and EOCOPD.
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:13 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  As shown in the resulting dataframe, there are some concept paths related to orthopnea that were not captured by the previous `orthopnea` search, such as `Do you sleep on 2 or more pillows to improve
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:13 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  You can get the phs number associated with each study from the Data Access Dashboard.
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:13 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/7_Harmonization_with_PICSURE.Rmd
>  We create a consistent mapping:
Resolved in R: [03295f8](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/03295f8b56a8ad3f9ba55180c4f8a2f8d37dde54)

2023-02-09 22:16 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  This cell rename signification of the variables that are being used throughout the notebook.
Resolved in R: [a15818f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/a15818fcd6a46aee7b7a4aa30728a47566a1788e)

2023-02-09 22:17 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/ORCHID_COVID19.Rmd
>  # Outcome Analysis
Resolved in R: [a15818f](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/a15818fcd6a46aee7b7a4aa30728a47566a1788e)

2023-02-09 22:19 UTC, simranmakwana commented on NHLBI_BioData_Catalyst/Rstudio/6_Sickle_Cell.Rmd
>  We are also interested in the patients' age at which they received their transplant. However, we do not want to filter our cohort based on these values. We can use the query.select method to add this
Resolved in rstudio: [d32ccf4](https://github.com/hms-dbmi/Access-to-Data-using-PIC-SURE-API/commit/d32ccf4fbfdbf85c6bb1102dacfcc29c22e148e4)

2023-02-25 20:06 UTC, emhug requested changes
Noticed some outdated documentation

2023-02-25 20:06 UTC, emhug commented on NHLBI_BioData_Catalyst/Rstudio/1_PICSURE_API_101.Rmd
>  There are several methods that can be used to build a query, which are listed below.
The following in-line documentation needs to be updated for the new functions

| Method | Arguments / Input | Output|
|--------|-------------------|-------|
| query.select.add() | variable names (string) or list of strings | all variables included in the list (no record subsetting)|
| query.require.add() | variable names (string) or list of strings | all variables; only records that do not contain null values for input variables |
| query.anyof.add() | variable names (string) or list of strings | all variables; only records that contain at least one non-null value for input variables |
| query.filter.add() | variable name and additional filtering values | input variable; only records that match filter criteria |

2023-02-25 20:06 UTC, emhug commented on NHLBI_BioData_Catalyst/R/1_PICSURE_API_101.ipynb
>    {
The following in-line documentation needs to be updated
| Method | Arguments / Input | Output|
|--------|-------------------|-------|
| query.select.add() | variable names (string) or list of strings | all variables included in the list (no record subsetting)|
| query.require.add() | variable names (string) or list of strings | all variables; only records that do not contain null values for input variables |
| query.anyof.add() | variable names (string) or list of strings | all variables; only records that contain at least one non-null value for input variables |
| query.filter.add() | variable name and additional filtering values | input variable; only records that match filter criteria |

2023-03-10 19:26 UTC, merged